#!/bin/bash
########################################
# Init and control script for Wakeify #
#   by Eric Thompson (October 2017)    #
########################################

FIND_PID="pgrep -u root -fo wakeify"
START_ALARM="python3 ./wakeify.py > /dev/null 2>&1 & disown"

do_start () {
	pid=$($FIND_PID)
	if [[ $pid ]]; then
		echo "Wakeify is already running with PID: $pid"
	else
		echo "Starting Wakeify..."
		$($START_ALARM)
	fi
}

do_status () {
	pid=$($FIND_PID)
	if [[ $pid ]]; then
		echo "Wakeify is running with PID: $pid"
	else
		echo "Wakeify is not currently running"
	fi
}

do_stop () {
	pid=$($FIND_PID)
	if [[ $pid ]]; then
		echo "Stopping Wakeify..."
		$(kill $pid) 
	else
		echo "Wakeify is not currently running"
	fi
}

case "$1" in
  start|"")
        do_start
        ;;
  restart|reload|force-reload)
        do_stop
        do_start
        ;;
  stop)
        do_stop
        ;;
  status)
        do_status
        exit $?
        ;;
  *)
        echo "Usage: wakeifyctl [start|stop|restart|status]" >&2
        exit 3
        ;;
esac
